#!/bin/bash

set -e

if [[ -n "${DHC_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Initial setup of development enviornment
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        pyenv local 3.12
        python -m venv .venv
    fi
fi
