#!/bin/bash

set -e

if [[ -n "${DHC_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Install deps and collect Django static files
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        pip install -r requirements.txt
    fi
fi
